name: CI

on:
  push:
    branches: [main]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          cache: "yarn"

      - run: yarn

      - run: yarn pub:canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
